apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb1
  name: myweb1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb1
  template:
    metadata:
      labels:
        app: myweb1
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
